# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11f0051f6724130cb4332f0704cfc8bd22b8a85e2ae696cd6cc60f5798d2dfbfbdb4dcfc472cc6186880287808bb3cc0e7751796671aa167bbef8681d1ad907a

test:
  secret_key_base: 99ffa3c93b3ed3a5830a7dc2e564a60df3885150a77e530ba181bbd58067c95eac968e96e69ab75f2cd92e414dcac2d09ab7afdf74d9152d51afd9878dc5033f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
